@startuml

[*] -right-> Open
Open -right-> ReadyForDelivery : ReceivePayment
Open -right-> ReadyForDelivery : UnlockDelivery
Open --> Canceled : Cancel
ReadyForDelivery -right-> Completed : Deliver (if paid)
ReadyForDelivery --> AwaitingPayment : Deliver (if !paid)
ReadyForDelivery --> Canceled : Refund (if paid)
ReadyForDelivery --> Canceled : Cancel (if !paid)
AwaitingPayment --> Completed : ReceivePayment
AwaitingPayment --> Canceled : Cancel
Completed --> Canceled : Refund
Canceled --> Open : Reopen

@enduml
